# Generated by Django 3.1 on 2020-08-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=122)),
                ('sex', models.CharField(max_length=122)),
                ('temperature', models.CharField(max_length=122)),
                ('assessment_date', models.DateField()),
                ('assessment_score', models.CharField(max_length=122)),
                ('covid19_result', models.CharField(max_length=122)),
            ],
        ),
    ]
